name: Django CD

on: 
  workflow_run:
    workflows: [ "Django CI" ]
    types:
      - completed

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:  
      - name: connect ec2
        uses: appleboy/ssh-action@master  # ssh 접속 라이브러리
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          envs: SECRET_KEY
          script: |
            cd /home/ubuntu/Django_lab
            source venv/bin/activate 
            cd /home/ubuntu/Django_lab
            pip install -r requirements.txt
            echo "< requirements.txt installed >"
            git pull
            echo "< pulled completed >"
            echo "{\"SECRET_KEY\": \"$SECRET_KEY\"}" > /home/ubuntu/Django_lab/secrets.json
            ls /home/ubuntu/Django_lab
            echo "< secrets.json file created >"
            nohup python manage.py runserver 0.0.0.0:8000 &
        
