name: Django CD

on: 
  workflow_run:
    workflows: [ "Django CI" ]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        # secrets.json 파일 생성
      - name: Generate secrets.json file
        run: |
          echo "{\"SECRET_KEY\": \"$SECRET_KEY\"}" >> secrets.json
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          
      - name: connect ec2
        uses: appleboy/ssh-action@master  # ssh 접속 라이브러리
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /home/ubuntu/Django_lab
            source venv/bin/activate
            cd /home/ubuntu/Django_lab
            pip install -r requirements.txt
            git pull
            nohup python manage.py runserver 0.0.0.0:8000 &
